### ISSUE TITLE
crash while dragging cells

### ISSUE THREAD

**Issue by smithani** [AlanQuatermain/AQGridView#1]
I'm experimenting with the code provided and it is really useful; however, I found that the sample (springboard) code crashes, if you reduce the number of icons down to 19, then try to move to an empty spot.

**Comment by AlanQuatermain** [comment]
Yeah, a friend at Apple found that too— it crashes in the sample when you drag down to the bottom (i.e. out of the actual allocated range). I think it's a simple fix: never try to move the empty cell placeholder beyond the bounds of the available cell list, i.e. MAX(attemptedCellIndex, numberOfCells-1).

I'll try to put a fix together for that today.

**Comment by smithani** [comment]
Thanks!

**Comment by AlanQuatermain** [comment]
Fixed [at this commit](http://github.com/AlanQuatermain/AQGridView/tree/c33a2ecc3df08b9948042010c917773806eca219).

AQGridViewData now returns NSNotFound when asked for a cell index based on a point which doesn't correspond to a real cell. The SpringBoard application now observes this return value and uses the index of the last cell in the list instead, which matches the behaviour of Apple's springboard. The same thing happens now if you drag a cell off the edge of the screen.
