### ISSUE TITLE
Possible to use a mixture of cells with different size?

### ISSUE THREAD

**Issue by acidz** [AlanQuatermain/AQGridView#101]
Is it possible to specify different cell sizes like how it is done in AppStart http://a2.mzstatic.com/us/r1000/035/Purple/d8/e2/d4/mzl.udqhjlyo.480x480-75.jpg?

portraitGridCellSizeForGridView only returns 1 cell size, so I have no idea where else to look into.

**Comment by evadne** [comment]
I’d rather say that in this case, you’ll have much smaller number of cells, but also less uniformity in cell sizes and dimensions that the best component would probably look very different from the grid view.
