### ISSUE TITLE
Cells get swapped around when CAAnimation is applied

### ISSUE THREAD

**Issue by jlstrecker** [AlanQuatermain/AQGridView#102]
http://stackoverflow.com/questions/8476945/aqgridview-cells-get-swapped-around-when-caanimation-is-applied

The behavior I'm getting sounds like the known bug with piling animations on top of each other, except I'm not sure that I am piling them on top of each other. There's just one animation per cell.

P.S. I've used AQGridView in several projects and other than this one problem it's been reliable and done exactly what I needed. Thanks for your work on this.

**Comment by evadne** [comment]
I guess a semi-clean but quite tacky way is to use CATransition.  Another solution is to do all the inference by yourself :p

http://monoceroi.tumblr.com/post/7311480915/springboard-style-aqgridview-rotation-take-2

**Comment by jlstrecker** [comment]
Thanks for the link. I was trying to animate individual cells, as opposed to the grid view as a whole -- but as you're showing, animating the grid view works. 

Based on that, I got a workaround -- create a copy of the grid view cell contents, then fade away the grid view. Kinda ugly, though. 

I'm not sure what you mean about using CATransition.

**Comment by evadne** [comment]
Aw, I mean CATransaction.

**Comment by evadne** [comment]
Closing as workaround found.
