### ISSUE TITLE
Calling reloadData causes all cells to blink

### ISSUE THREAD

**Issue by ralphleon** [AlanQuatermain/AQGridView#110]
Calling reload data on the main thread causes the grid view cells to "blink" (turn white) in a way that is very noticeable to the user.

**Comment by evadne** [comment]
Triage: device, version, code, reproduction?

:)

On Jan 26, 2012, at 10:36, Ralph Gootee
reply@reply.github.com
wrote:

**Comment by ralphleon** [comment]
Fair enough:  Simulator & Hardware, 4.3 and 5.0, if it's not obviously reproducible than it's probably my fault ;)

**Comment by evadne** [comment]
Guess it’s because Core Animation actually drew something – because something has spun the run loop (likely runaway -performSelector:withDelay: calls, if that’s even possible) – but I’d like to see it live. :)

**Comment by ralphleon** [comment]
Let me see if I can whip something up, It's probably because I implemented lazy image loading (that should be built in to a lib like this).  I don't have it hooked into a cache yet -- so that's probably the issue.  Is there any interest of having things like this in the library?  For my use case, it stopped performing well on 30 images (256x256) without using core graphics to lazy image load.

**Comment by evadne** [comment]
There seems to be no blinking with stock samples that ship with the grid view, so there’s probably some misleading omissions in the documentation, or so.  Haven’t squinted yet.

It’s almost a nust-have for networked apps, but let’s not put it in the grid view, or it will look like a kitchen sink. ;)  I’ve personally got pretty good performance with hundreds / thousands of cells.

**Comment by ralphleon** [comment]
Meh, it's an issue for me, so I'll just close this.

**Comment by CodyKolodziejzyk** [comment]
I am getting this issue right now with my lazy image loading implementation. I use the same implementation in a UITableView with lazy image loading and do not see the same issue. I am setting the cell's image URL property in cellForItemAtIndex, and then checking if they are the same in the setter with this code:
- (void)setImageURL:(NSURL *)url
  {
  
  if ([_imageURL isEqual:url] && self.imageView.image != nil) return;  
  
    //Then I grab the image from the cache

}

When I call reloadData, the cells should not blink if the image is still the same right? As I said, I am using the same implementation in a uitableview and I do not see a blink.

**Comment by evadne** [comment]
First try comparing -absoluteString.  Second, you might get around this
issue by sharing an image URL — blob cache hash so images already loaded
can be pulled out instantly.

On 2012-08-30, at 15:40, CodyKolodziejzyk notifications@github.com wrote:

I am getting this issue right now with my lazy image loading
implementation. I use the same implementation in a UITableView with lazy
image loading and do not see the same issue. I am setting the cell's image
URL property in cellForItemAtIndex, and then checking if they are the same
in the setter with this code:
- (void)setImageURL:(NSURL *)url { if ([_imageURL isEqual:url] &&
  self.imageView.image != nil) return;

When I call reloadData, the cells should not blink if the image is still
the same right? As I said, I am using the same implementation in a
uitableview and I do not see a blink.

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/issues/110#issuecomment-8177164.

**Comment by CodyKolodziejzyk** [comment]
I tried comparing absoluteString but I get the same result. Why doesn't this happen in a UITableView but it happens here?

**Comment by AlanQuatermain** [comment]
I don't recall offhand, but does -reloadData go through the full cell recycling dance, meaning -prepareForReuse gets sent to all the existing cells, thus making them invalidate their images?

On 2012-08-31, at 2:28 PM, CodyKolodziejzyk notifications@github.com wrote:

> I tried comparing absoluteString but I get the same result. Why doesn't this happen in a UITableView but it happens here?
> 
> —
> Reply to this email directly or view it on GitHub.

Cheers,
-Jim

jimdovey@(mac|gmail).com
http://twitter.com/alanQuatermain
http://github.com/alanQuatermain
http://stackoverflow.com/users/103900/jim-dovey
http://ca.linkedin.com/pub/jim-dovey/2/24b/883

**Comment by CodyKolodziejzyk** [comment]
I don't believe so. -prepareForReuse is only called in -dequeueReusableCellWithIdentifier

**Comment by AlanQuatermain** [comment]
Does -reloadData: dump all the current cells into the reuse queue?

On 2012-08-31, at 2:58 PM, CodyKolodziejzyk notifications@github.com wrote:

> I don't believe so. -prepareForReuse is only called in -dequeueReusableCellWithIdentifier
> 
> —
> Reply to this email directly or view it on GitHub.

Cheers,
-Jim

jimdovey@(mac|gmail).com
http://twitter.com/alanQuatermain
http://github.com/alanQuatermain
http://stackoverflow.com/users/103900/jim-dovey
http://ca.linkedin.com/pub/jim-dovey/2/24b/883

**Comment by CodyKolodziejzyk** [comment]
Yep, it dumps all visible cells into the reuse queue I believe. This is where it happens in -reloadData:

// remove all existing cells
[_visibleCells makeObjectsPerformSelector: @selector(removeFromSuperview)];
[self enqueueReusableCells: _visibleCells];
[_visibleCells removeAllObjects];

-prepareForReuse simply sets the cell's shadowPath to 0, which shouldn't invalidate the cell's image right? I think I'm in a little over my head but I'm trying to comprehend the code as best as I can.

**Comment by AlanQuatermain** [comment]
Yeah, the default implementation of -prepareForReuse does that; have you overridden it in your cell subclass (you usually should).

On 2012-08-31, at 3:14 PM, CodyKolodziejzyk notifications@github.com wrote:

> Yep, it dumps all visible cells into the reuse queue I believe. This is where it happens in -reloadData:
> 
> // remove all existing cells
> [_visibleCells makeObjectsPerformSelector: @selector(removeFromSuperview)];
> [self enqueueReusableCells: _visibleCells];
> [_visibleCells removeAllObjects];
> 
> -prepareForReuse simply sets the cell's shadowPath to 0, which shouldn't invalidate the cell's image right? I think I'm in a little over my head but I'm trying to comprehend the code as best as I can.
> 
> —
> Reply to this email directly or view it on GitHub.

Cheers,
-Jim

jimdovey@(mac|gmail).com
http://twitter.com/alanQuatermain
http://github.com/alanQuatermain
http://stackoverflow.com/users/103900/jim-dovey
http://ca.linkedin.com/pub/jim-dovey/2/24b/883

**Comment by CodyKolodziejzyk** [comment]
I have not overwritten it yet. is this what could be causing the flickering?

**Comment by AlanQuatermain** [comment]
That's my guess— there's no guarantee that the same cells will be placed in the same positions after they've been dropped into the reuse queue.

On 2012-08-31, at 3:27 PM, CodyKolodziejzyk notifications@github.com wrote:

> I have not overwritten it yet. is this what could be causing the flickering?
> 
> —
> Reply to this email directly or view it on GitHub.

Cheers,
-Jim

jimdovey@(mac|gmail).com
http://twitter.com/alanQuatermain
http://github.com/alanQuatermain
http://stackoverflow.com/users/103900/jim-dovey
http://ca.linkedin.com/pub/jim-dovey/2/24b/883

**Comment by rlam3** [comment]
+1

**Comment by Ankish** [comment]
+1
