### ISSUE TITLE
Vertical Scrolling Problem

### ISSUE THREAD

**Issue by flexaddicted** [AlanQuatermain/AQGridView#115]
I have the following structure.

An UINavigationController pushes a UIViewController with a xib with the following hierarchy:

-- UIView
--- AQGridView

AQGridView doesn't snap to the correct position (top one) after the bouncing animation have finished each time it is scrolled. The navigation bar of the UINavigationController overlaps the content displayed in the grid view.

**Comment by evadne** [comment]
Also — the XIB.

**Comment by evadne** [comment]
Please post the code.  Thanks.

**Comment by flexaddicted** [comment]
I'm sorry. How can I post the code? Thank you in advance.

**Comment by evadne** [comment]
Could you create a GitHub repository and put your code there?

**Comment by flexaddicted** [comment]
Ok, I'll do as soon as possible. Thank you again.
