### ISSUE TITLE
Static analysis errors

### ISSUE THREAD

**Issue by BenParks** [AlanQuatermain/AQGridView#116]
Hi all,

I've just downloaded this component and got it working.. and it seems to be working well.

However when I do a static analysis on the code I get 25+ potential leaks.

For example in AQGridViewController :
- (void) loadView
  {
  AQGridView \* aView = [[AQGridView alloc] initWithFrame: CGRectZero];
  self.gridView = aView;
  
  [self _sharedGridViewDefaultSetup];
  }

aView is being leaked here isn't it?

What am I doing wrong?

Thanks,
Ben

**Comment by evadne** [comment]
Nothing :)  I think the project has been converted to use ARC (automatic reference counting) where -dealloc and -autorelease calls are generated and they were therefore removed.

**Comment by BenParks** [comment]
Ann, I see thanks.

So what are my options? Can I create a lib and static link to it from an non ARC project?

Thanks,
Ben

**Comment by BenParks** [comment]
Just to complete this..

I referenced the main AQGridView project from my (non ARC) project. I then ran some tests with Instruments and I think I've convinced my self this approach will work.

Longer term I'll migrate the host project to use ARC.
