### ISSUE TITLE
ARC Issues in AQGridView

### ISSUE THREAD

**Issue by idevtech** [AlanQuatermain/AQGridView#118]
When trying to convert my project to ARC the following warnings are generated:

AQGridViewCell.m (line 97)

Method possibly missing a [super dealloc] call

AQGridViewUpdateInfo.m (line 67)

Method possibly missing a [super dealloc] call

Adding these two method calls makes AQGridView pass the ARC conversion check.

**Comment by evadne** [comment]
This is because the grid view already uses ARC.

On Mar 7, 2012, at 1:40, idevtech
reply@reply.github.com
wrote:

**Comment by idevtech** [comment]
Since AQGridView in in my project it prevents me from converting my project
since it does not pass the ARC conversion test. What should I do?

Thanks
Chris

On Tue, Mar 6, 2012 at 6:34 PM, Evadne Wu <
reply@reply.github.com

**Comment by evadne** [comment]
The best thing to do is to include it as a static library then you can
toggle ARC on or off independently.

On Mar 7, 2012, at 8:42, idevtech
reply@reply.github.com
wrote:

**Comment by amieka** [comment]
You can turn on/off ARC for individual files in Xcode using the following flag -fno-objc-arc

**Comment by evadne** [comment]
Toggling individual files on and off is fine, but then if anybody added a file to the project, every single dependent which included a bunch of files in the root level will have to change.  We already ship a static library, so use that instead.  It also provides some sort of insulation against code decay where we can target SDKs and deployment targets independently.

**Comment by evadne** [comment]
Closing.  (Feel free to re-open this issue.)
