### ISSUE TITLE
UIPopover reference crashes on iphone

### ISSUE THREAD

**Issue by funkyboy** [AlanQuatermain/AQGridView#12]
Hi,

on iphone 3g (os 3.1) the app crashes because of the references to UIPopoverController.
Target sdk is 3.2. Deploy sdk is 3.0
How can I fix it?

-c.

**Comment by AlanQuatermain** [comment]
Ah, I'll sort that out for you now.

**Comment by AlanQuatermain** [comment]
Actually, I'm looking at the Kobo code right now and we're using exactly the same thing, with no changes. The only difference I can see is that we're building against the 4.0 SDK, but we still deploy on OS 3.0+, and the popover delegation protocol and suchlike don't appear to cause us any trouble.

Are you using GCC or LLVM to compile your project? There might be a difference there.

**Comment by AlanQuatermain** [comment]
Actually, I can't figure out what that was in there for-- evidently something which has since been removed. So I've removed all the popover stuff from AQGridViewController completely.

**Comment by funkyboy** [comment]
I remove it too. Then I weakly linked uikit (the only way to get rid of the error).
In this case I get another error: 

CALayer setShadowColor: unrecognized selector sent to instance

This happens when i use llvm 1.5 or gcc 4.2
I am building against 4.0 sdk and deploy to 3.1.3

Any idea?

ps: Only iPad specific classes contain references to UIPopover

**Comment by funkyboy** [comment]
That was another part of my code. Solved.
Thanks!
