### ISSUE TITLE
BUG: EXC_BAD_ACCESS crash in touchesEnded: ( see SpringBoard demo )

### ISSUE THREAD

**Issue by spiderr** [AlanQuatermain/AQGridView#129]
Run SpringBoard.xcodeproj 

Touch and hold any colored rectangle and drag to a new location.

Tap and release on any other rectangle. (Tap and drag other rectangle works.)

BOOM! EXC_BAD_ACCESS right here:

```
- (void) touchesEnded: (NSSet *) touches withEvent: (UIEvent *) event
{
  [[self class] cancelPreviousPerformRequestsWithTarget: self
                                                 selector: @selector(_gridViewDeferredTouchesBegan:)
                                                   object: nil];

    UIView * hitView = _touchedContentView;
```

Been hunting this down thinking it was my own code.  _touchedContentView is holding on to dealloced memory?

Running XCode 4.3.1 for ARC enabled iOS 5.1 project.

**Comment by spiderr** [comment]
Anyone...? Bueller?

**Comment by dolfin** [comment]
I'm having this issue too. Looking forward for a solution.

**Comment by spiderr** [comment]
This isn't a solution, per se. I spent time trying to sort it out, however I ultimately dropped AQGridView because of this, and migrated to https://github.com/ultragtx/GSBookShelf - seems to work great.

**Comment by TA2k** [comment]
a workaround is to change 
in line 116 in AQGridView.h "__unsafe_unretained" to "__strong"

**Comment by jsumners** [comment]
You don't even have to move a rectangle to introduce the bug. Simply "pick up" a rectangle, "drop" it, and then tap it (like it would open an application).

**Comment by evadne** [comment]
This is a very bad bug related to the earlier ARC conversion and use of an unsafe and unretained faux “weak” reference.  Hopefully we’ll be able to fix it very soon.

**Comment by evadne** [comment]
This issue should now be partially resolved on the `develop` branch.  (“Crash is gone.”)

I’m seeing artifacts related to drop animation using the wrong rect (cell index off by one) in some edge cases in SpringBoard and zapping the cells prematurely, triggering a recreation process; those issues will be resolved later.

Thanks!

**Comment by evadne** [comment]
Closing issue: tracking SpringBoard progress separately.
