### ISSUE TITLE
Repeating background?

### ISSUE THREAD

**Issue by jdmuys** [AlanQuatermain/AQGridView#13]
I am playing with AQGridView to try to replicate a IBooks-like look and feel, with shelves and the like. I can't manage to display the background shelves properly:
- resizing dynamically as the number of cells vary
- scrolling in sync with the cells
- respecting orientation, header and footer
- with fixed-size left and right "shelf walls"

I am about to develop a custom tiling UIView subclass to set as the background view. Would that be the correct approach?

TIA

Jean-Denis

**Comment by AlanQuatermain** [comment]
Rather than tiling things manually, just use `+[UIColor colorWithPatternImage:]` to create a color from the image you want to tile, and set that as the background colour for a plain UIView which you set as the gridview's `-backgroundView` property. That's what we do at Kobo for our shelves. So:

```
UIImage * patternTile = [UIImage imageNamed: @"MyShelfTile.png"];
UIView * backgroundView = [[UIView alloc] init];
backgroundView.backgroundColor = [UIColor colorWithPatternImage: patternTile];
self.gridView.backgroundView = backgroundView;
[backgroundView release];
```

**Comment by lightandshadow68** [comment]
+[UIColor colorWithPatternImage:] works for a small number of cells, but memory requirements can be prohibitive with a large number of cells.
