### ISSUE TITLE
Can I create the grid view and cells view using storyboard?

### ISSUE THREAD

**Issue by Ricardo1980** [AlanQuatermain/AQGridView#131]
Can I create the grid view and cells view using storyboard instead of writing code in initWithFrame or viewDidLoad?
Thanks.

**Comment by evadne** [comment]
Not now.

On May 7, 2012, at 10:16, Ricardo1980
reply@reply.github.com
wrote:

**Comment by evadne** [comment]
Actually yes but you can only hook the grid view on.  The cell itself
needs to be instantiated for use in the controller with code.  Your
cell subclass can use UINib in a convenience method to support
instantiation from XIB.

On May 7, 2012, at 10:16, Ricardo1980
reply@reply.github.com
wrote:

**Comment by Ricardo1980** [comment]
Does this mean, if I use sotoryboard, I should create a separate XIB file for cells? Which is not wonderful but from far better than hard code them. 

The cells I want to create are a little bit complex. Hard code them is too much painful. 

Any suggestion? Thanks.

**Comment by evadne** [comment]
You can and that might actually be a good idea.  :)

On May 7, 2012, at 10:30, Ricardo1980
reply@reply.github.com
wrote:

> Does this mean, if I use sotoryboard, I should create a separate XIB file for cells? Which is not wonderful but from far better than hard code them.
> 
> The cells I want to create are a little bit complex. Hard code them is too much painful.
> 
> Any suggestion? Thanks.
>

**Comment by Ricardo1980** [comment]
Last question. Can I use storybord to create cells? So everything is more consistent. In this case, where put exactly the cell view? Thanks.

**Comment by evadne** [comment]
Never tried but I think you can only create a prototype, which gets
referenced and copied, otherwise since the storyboard instantiates
view controllers it is going to be unwieldy.

On May 7, 2012, at 12:45, Ricardo1980
reply@reply.github.com
wrote:

> Last question. Can I use storybord to create cells? So everything is more consistent. In this case, where put exactly the cell view? Thanks.
>

**Comment by evadne** [comment]
Closing issue: I’m pretty sure using storyboards to create cell prototypes is a bag of hurt.  (Which is unfortunate.)
