### ISSUE TITLE
Please add semantic version tags

### ISSUE THREAD

**Issue by lexrus** [AlanQuatermain/AQGridView#136]
@garnett has recently added [`<AQGridView>`](https://github.com/AlanQuatermain/AQGridView) to the [CocoaPods](https://github.com/CocoaPods/CocoaPods) package manager repo.

CocoaPods is a tool for managing dependencies for OSX and iOS Xcode projects and provides a central repository for iOS/OSX libraries. This makes adding libraries to a project and updating them extremely easy and it will help users to resolve dependencies of the libraries they use.

However, `<AQGridView>` doesn't have any version tags. He/She has added the current HEAD as version 1.2, but a version tag will make dependency resolution much easier.

[Semantic version](http://semver.org) tags (instead of plain commit hashes/revisions) allow for [resolution of cross-dependencies](https://github.com/CocoaPods/Specs/wiki/Cross-dependencies-resolution-example).

In case you didn’t know this yet; you can tag the current HEAD as, for instance, version 1.2, like so:

```
$ git tag -a 1.2 -m "Tag release 1.2"
$ git push --tags
```

**Comment by delebedev** [comment]
Done.

**Comment by lexrus** [comment]
Are you sure? I didn't see any tag in this repo yet.

**Comment by delebedev** [comment]
Sorry, I misunderstood you and have added the tag to my CocoaPods fork:(

**Comment by evadne** [comment]
Closing: this shall have landed (as of 1.3).  Thanks!

**Comment by kevinrenskers** [comment]
Shouldn't there be a new version / tag soon with the latest 3 commits? They are quite old, a 1.3.1 tag would be very welcome so we can continue to use CocoaPods to install AQGridView.
