### ISSUE TITLE
UISearchBar with contentInset breaks it's “autofocus”

### ISSUE THREAD

**Issue by dmrschmidt** [AlanQuatermain/AQGridView#137]
I have a UISearchBar inside of an AQGridView. Now the searchBar shall be hidden initially (as you see in the Music app for instance). As AQGridViews (or UIScrollViews) don't have a header view, I placed it -40 points outside of the AQGridView's frame and also set the contentInset to 40 points.

```
searchBar = [[UISearchBar alloc] initWithFrame:CGRectMake(0.f, -40.f, 320.f, 40.f)];
gridView.contentInset = UIEdgeInsetsMake(0.f, 40.f, 0.f, 0.f);
```

Now from the look and general behavior that pretty much does exactly what I want. The search bar is hidden, but I can scroll up to reveal it.

Now here's the thing:

When I touch on the searchBar to give it focus and enter some text everything works fine except when the searchBar is not entirely visible. In that case the UIScrollView tries to automatically scroll it to complete visibility. However, it scrolls in the wrong direction.

So when, say, 10 points on top of the search bar are hidden, the scroll view scrolls down instead of up. Actually the first time I click on the search bar, it scrolls 40 points up, just without any animation and a subtle delay (even on the simulator). All following times the described scrolling downwards happens.

There's also a stackoverflow thread on that topic where it's been suggested this is probably a bug in AQGridView. http://stackoverflow.com/questions/10730431/uiscrollview-with-contentinset-breaks-uisearchbar-autofocus#comment13940021_10730431

**Comment by evadne** [comment]
Unfortunately I can confirm that there has been issues regarding using the grid view with edge insets — the only edges you can safely inset are the left and right edges, and even for those edges you must inset with a zero or positive length.

There’s a workaround that has been tested to work on iOS 5 / 6 (GM) though:
- place the grid view in a containing view with space above it.
- set clipping to NO.
- place view within the grid view but above its top bounds.

I’ll be closing this issue for now as a new one has been created: https://github.com/AlanQuatermain/AQGridView/issues/164 — however, feel free to re-open this issue for more data specific to this error case.  Thanks again for reporting.
