### ISSUE TITLE
-[CFDictionary objectForKey:]: message sent to deallocated instance

### ISSUE THREAD

**Issue by lukaszmargielewski** [AlanQuatermain/AQGridView#139]
On AQGridView layuotSubviews application crashes. trace stops in AQGridViewCell makeSubviewsOfViewOpaqueAgain in line 223
Is that an ARC issue? (I am not using ARC in my project).

**Comment by lukaszmargielewski** [comment]
This helped:
1. Added [[cell retain] autorelease] in dequeueReusable....
- (AQGridViewCell *) dequeueReusableCellWithIdentifier: (NSString *) reuseIdentifier
  {
  NSMutableSet \* cells = [_reusableGridCells objectForKey: reuseIdentifier];
  AQGridViewCell \* cell = [cells anyObject];
  if ( cell == nil )
      return ( nil );
  
  [cell prepareForReuse];
  
  [[cell retain] autorelease];
  [cells removeObject: cell];
  return ( cell );
  }
1. Changed AQGridViewCell dealloc to (CGRelease commented and added [super dealloc]:
   - (void) dealloc
     {
     //if ( _selectionColorInfo != NULL )
     //CFRelease( _selectionColorInfo );
   
   [super dealloc];
   }

However, I am getting small memory leaks. I HAve not moved myself to ARC yet so I am not sure if it the ARC issue.
I will be very pleased to see advice.

**Comment by evadne** [comment]
Thanks for the report.  Unfortunately the report is not clear about which commit of AQGridView you’re on — please provide more information and re-open this issue.
