### ISSUE TITLE
Is AQGrid ARC-based? README?

### ISSUE THREAD

**Issue by claybridges** [AlanQuatermain/AQGridView#141]
I'm assuming AQGridView is now fully ARC-ified, but I kind of have to guess, b/c there is nothing in the README. Given the transition period we are going through, this info really needs to be front-and-center.

**Comment by evadne** [comment]
It’s using ARC.  Please file an issue for updating the README, or just fork the project, update it and send a pull request.  Thanks!

**Comment by claybridges** [comment]
Which commit is 1.2? (cf. my other [issue](https://github.com/AlanQuatermain/AQGridView/issues/144) on version tags). CocoaPods says it is commit id `f6c5589a6dabfff693fc7def7342327b9b0df3f9`, but the 10 Jan 2012 date on the README makes me think it is the last commit before then: `fe01193d263788602015dbc42046b30276e60c84`.

**Comment by evadne** [comment]
Wait — that’s terrible, we did have versioning once upon a time?

**Comment by evadne** [comment]
Closing the issue for now.  As of now, AQGridView 1.3 (b3270c6) is the latest stable release, and more code has been pushed to the develop branch.  As of version 1.3  the project is under ARC.

Feel free to re-open this issue if something does not add up — and thanks for reporting!
