### ISSUE TITLE
ARC-based library vs. non-ARC ExpanderDemo

### ISSUE THREAD

**Issue by claybridges** [AlanQuatermain/AQGridView#142]
Is giving 2 warnings, e.g.

```
[path]/AQGridView/Examples/ExpanderDemo/Classes/../../../Classes/AQGridViewCell.m:101:1: 
warning: method possibly missing a [super dealloc] call [-Wobjc-missing-super-calls]
```

**Comment by evadne** [comment]
Probably need flags.

On Jul 7, 2012, at 2:33, Clay Bridges
reply@reply.github.com
wrote:

**Comment by evadne** [comment]
This looks like an issue with using old versions of Xcode / clang / iOS SDK.  I’ll be closing this issue for now — but please do re-open it (and provide information of your environment) if that’s still happening with either Xcode 4.4 or 4.5.
