### ISSUE TITLE
Version tags?

### ISSUE THREAD

**Issue by claybridges** [AlanQuatermain/AQGridView#144]
I didn't see any. Am I missing something obvious?

That would make the version commit explicit, and avoid, e.g. the CocoaPods spec needing to link to a commit id:

Maybe I missed something, but I don't see any version tags (I did 'git pull origin --tags)Would version tags makes sense? That would make the version That would avoid e.g. CocoaPods having to link to a commit id:

```
Pod::Spec.new do |s|
  s.name     = 'AQGridView'
  s.version  = '1.2'
  s.license  = 'BSD'
  s.summary  = 'A grid view for iPhone/iPad, designed to look similar to NSCollectionView.'
  s.homepage = 'https://github.com/AlanQuatermain/AQGridView'
  s.author   = { 'Alan Quatermain' => 'jimdovey@mac.com' }
  s.source   = { :git => 'git://github.com/AlanQuatermain/AQGridView.git', :commit => 'f6c5589a6dabfff693fc7def7342327b9b0df3f9' }
  s.platform = :ios
  s.requires_arc = true
  s.source_files = 'Classes'
  s.resources = "Resources/*.png"
  s.clean_paths = "Examples", "Scripts", "AQGridView.xcodeproj", "AQGridView_Prefix.pch"
  s.framework = 'QuartzCore'
end
```

**Comment by evadne** [comment]
Honestly we’re not even doing dot / build number style versioning — commit SHAs are probably good enough?

**Comment by claybridges** [comment]
My simple rule: if it confused me, it will confuse others. Honestly, other than digging into CocoaPods, how am I supposed to know? 

I can push a `v1.2` tag if you want.

**Comment by evadne** [comment]
Agreed, but we’re kind of comfortable with just using commit SHAs.

How about forgetting about 1.2 and tagging the current commit that `master` points to as 1.3.

**Comment by claybridges** [comment]
Reasonable, done. Is 1.3 stable, i.e. the new marquis release? If so, I'll push changes to README as well, referring to 1.3.

**Comment by evadne** [comment]
It’s reasonable to just tag this thing as 1.3.  Stable?  No, but we need a solid reference point.

I am thinking of doing some work, closing all the pull requests, and have a spring-cleaning release for 1.4.  Which will be called “stable” then.

Thanks again!

**Comment by claybridges** [comment]
I forgot, pull-requests don't do tags. I'll see what I can figure out.

**Comment by evadne** [comment]
I can stitch them manually post-facto.  :)

On Jul 7, 2012, at 5:32, Clay Bridges
reply@reply.github.com
wrote:

**Comment by claybridges** [comment]
It might be easier (not just for me; you too) for somebody with admin privs on the main probject on github to create the tag using the web GUI. It's dead easy, & github pull requests don't seem to have any love for tag-only patches, that I can tell.

**Comment by evadne** [comment]
yep.

**Comment by claybridges** [comment]
Ping. Can somebody with admin privs create a 1.3 tag? Once done, I'll reward you by creating a new podspec myself.

**Comment by evadne** [comment]
Sorry, totally my fault.  It has been pushed to master.  Thanks!

**Comment by orta** [comment]
I made this podspec, this issue can be closed.

**Comment by evadne** [comment]
Thanks @orta @claybridges .  Closing.
