### ISSUE TITLE
Support loading GridViewCell from a nib

### ISSUE THREAD

**Issue by jasperblues** [AlanQuatermain/AQGridView#145]
Hi, 

Does AQGridViewCell support loading the cell from a nib? 

I tried, but the layout was bad. I think it had something to do with not injecting the contentView container correctly. I changed to a nibless view, and that worked fine. 

Is there a tried and true approach for nibs? 

Jasper

**Comment by evadne** [comment]
How about saying that you can bend the cell’s will into loading itself
from a nib?  Yes, but I believe that either I am the only person
abusing the approach or it has not been properly documented.

Content view not being injected properly sounds peculiar.  Would you
elaborate on your setup?

On Jul 26, 2012, at 10:38, Jasper Blues
reply@reply.github.com
wrote:

**Comment by jasperblues** [comment]
That's right - I promise the cell that good things will happen, if it will only load from a nib. . . I'm using code now, but my setup before was: 
1. deque the cell. If it is nill then: 

@property (nonatomic, weak) IBOutlet ActivityGridViewCell\* injectedCell; 

 [[NSBundle mainBundle] loadNibNamed:@"ActvityGridViewCell" owner:self options:nil];
        cell = self.injectedGridViewCell;
        self.injectedGridViewCell = nil;
        [cell setReuseIdentifier:PlainCellIdentifier];
        cell.selectionGlowColor = [UIColor purpleColor];
        [cell setFrame:CGRectMake(0.0, 0.0, 248.0, 312.0)];

. . . but I think the cell loaded from the nib has a root view called 'view', while an AQGridViewCell has a root view called 'contentView'  

Jasper Blues
Landline: +63.2.826.2489
Skype: jasperblues
LinkedIn Twitter

**Comment by evadne** [comment]
Are you still around?  I made a screencast about this.

https://vimeo.com/46408155

Best,
Eve

**Comment by jasperblues** [comment]
Thanks - I'll check it out!

**Comment by mtitolo** [comment]
I figured out a workaround for this.

Firstly, either set your reuseIdentifier in `cellForItemAtIndex:`, or add a `- (void)reuseIdentifier` to your subclass.

Second, add `@property (nonatomic, readonly, retain) IBOutlet UIView * contentView;` to your subclass's .h. Then create a view for it in your nib, connect it, and do all of your work from there. I haven't tried this with custom backgrounds, admittedly.

Still a :+1: for adding official support.

**Comment by evadne** [comment]
Wonderful.  Connecting the `contentView` is probably the right way.  Here’s a screencast though: https://vimeo.com/46408155

**Comment by evadne** [comment]
Closing issue, tracking related reqs in #169.
