### ISSUE TITLE
delete image in the image demo sample

### ISSUE THREAD

**Issue by murad1981** [AlanQuatermain/AQGridView#147]
How can i delete any image in the image demo sample (that is downloaded with AQGridView) ? 
thank you so much in advance ...

**Comment by evadne** [comment]
Just duplicate the folder then delete them.

On Jul 26, 2012, at 17:04, unpresedented
reply@reply.github.com
wrote:

**Comment by murad1981** [comment]
there is option to duplicate the folder ? how to duplicate it ?

**Comment by evadne** [comment]
clone the project, make a copy in Finder.

**Comment by murad1981** [comment]
I don't ask how to clone a project ... I'm asking how to implement the deletion of photos in the image demo sample project

**Comment by evadne** [comment]
Oh, please file an issue (enhancement request).

On Jul 26, 2012, at 18:31, unpresedented
reply@reply.github.com
wrote:

**Comment by murad1981** [comment]
where can I file this request please ? do you have any idea on how to do it instead of waiting too much time for the commiter to commit this feature ?

**Comment by evadne** [comment]
The feature is already there in AQGridView.  File an enhancement
request against the sample.  File it in the project’s Issues tab.

Best,
Eve

On Jul 26, 2012, at 18:38, unpresedented
reply@reply.github.com
wrote:

**Comment by evadne** [comment]
For your information use this method:

```
- (void) deleteItemsAtIndices: (NSIndexSet *) indices
```

withAnimation: (AQGridViewItemAnimation) animation;

This is in AQGridView.h .

On Jul 26, 2012, at 18:38, unpresedented
reply@reply.github.com
wrote:

**Comment by murad1981** [comment]
Eve, can you point me where exactly this feature is available in code ? so  i can incorporate it in my project ...

**Comment by evadne** [comment]
It is on AQGridView.h.

On Jul 26, 2012, at 18:49, unpresedented
reply@reply.github.com
wrote:

**Comment by murad1981** [comment]
thank you so much ...
