### ISSUE TITLE
embed_png.sh error

### ISSUE THREAD

**Issue by pzmudzinski** [AlanQuatermain/AQGridView#148]
Hey, I went through install tutorial but can't get rid of error from embed_png script: 
/Users/me/Desktop/aqproject/AQGridView/Scripts/embed_png.sh: line 2: 
: command not found
/Users/me/Desktop/aqproject/AQGridView/Scripts/embed_png.sh: line 4: 
: command not found
/Users/me/Desktop/aqproject/AQGridView/Scripts/embed_png.sh: line 7: 
: command not found
/Users/me/Desktop/aqproject/AQGridView/Scripts/embed_png.sh: line 8: cd: Resources
: No such file or directory
/Users/me/Desktop/aqproject/AQGridView/Scripts/embed_png.sh: line 9: syntax error near unexpected token `do
'
/Users/me/Desktop/aqproject/AQGridView/Scripts/embed_png.sh: line 9:`for png in *; do
'

In my project folder I got AQGridView\Resources and AQGridView\Scripts as well - any ideas? 
Thanks!

**Comment by evadne** [comment]
Images are basically axed.  Would you mind sharing which tutorial?  It might also need to be fixed or removed.

Thanks!

**Comment by pzmudzinski** [comment]
Oh, I meant tutorial placed on homesite / readme file - "How to use it in your project". Additionaly libAQGridView.a is highlighted in red. Do you have any idea what I have might done wrong?

**Comment by evadne** [comment]
Which branch are you on?

**Comment by pzmudzinski** [comment]
Master - didn't change anything.

**Comment by evadne** [comment]
That’s too bad.  Try `develop` which has a new `README`, and follow that version.  

Best,
Eve

**Comment by pzmudzinski** [comment]
Thanks, I'll try this.

**Comment by evadne** [comment]
Closing: embedded images removed as collateral damage from iOS 5.0+ modernization support.  Feel free to reopen if you rely on this feature and could not do a cherry-pick or compile the app against an older version.  Thanks!
