### ISSUE TITLE
Initializing AQGridViewController for a UIPopupController.

### ISSUE THREAD

**Issue by SquaredTiki** [AlanQuatermain/AQGridView#15]
AQGridViewController cannot be used in a Pop Up like a Normal Table View can.
This code does not work. 

```
fileTypePicker = [[[FileTypeViewController alloc] initWithStyle:UITableViewStylePlain] autorelease];
fileTypePicker.delegate = self;
self.fileTypePopover = [[[UIPopoverController alloc] initWithContentViewController:fileTypePicker] autorelease]
[self.fileTypePopover presentPopoverFromBarButtonItem:sender permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES]; 
```

Specifically `initWithStyle:` which crashes the App. How is the issue solved?

**Comment by AlanQuatermain** [comment]
On what are you calling -initWithStyle: ? That's a UITableViewController method, AQGridViewController doesn't have that.

AQGridViewController can absolutely be used in a popup controller; just initialize the view controller and place it in a popover. It doesn't implement the exact same interface as UITableViewController is all.

**Comment by SquaredTiki** [comment]
I am calling `initWithStyle:` on a AQGridViewController called FileTypeViewController. How would I initialize it instead?

**Comment by AlanQuatermain** [comment]
As you can see looking at the header (http://github.com/AlanQuatermain/AQGridView/blob/master/Classes/AQGridViewController.h) it's just a subclass of UIViewController. That means that you would initialize it with either initWithNibName:bundle: or (if you're not using a min file, and IT sounds like you aren't) you would just use -init.

**Comment by SquaredTiki** [comment]
Thanks.
