### ISSUE TITLE
Unable to scroll empty gridView

### ISSUE THREAD

**Issue by iprebeg** [AlanQuatermain/AQGridView#150]
Why gridView can't be scrolled if empty anymore? This breaks ability to implement pullToRefresh and similar, looking into code for two hours and can't figure what is causing this. Any hints?

Edit: It can't be scrolled not just if empty but also if contentSize is not bigger than bounds.size.

**Comment by evadne** [comment]
I an guessing either contentSize or alwaysBouncesVertically.  Might be a
general UIScrollView thing.  Do you have a sample app?

On Aug 16, 2012, at 16:27, iprebeg notifications@github.com wrote:

Why gridView can't be scrolled if empty anymore? This breaks ability to
implement pullToRefresh and similar, looking into code for two hours and
can't figure what is causing this. Any hints?

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/issues/150.

**Comment by iprebeg** [comment]
Hi evadne,

try scrolling ExpanderDemo before expanding it.

Thank you for your answer.

**Comment by iprebeg** [comment]
alwaysBouncesVertically was something I missed, thank you
