### ISSUE TITLE
Distinguish long press from short selection

### ISSUE THREAD

**Issue by hohl** [AlanQuatermain/AQGridView#154]
Is there a way to distinguish between a long press (for showing a options menu) and a short tap for a selection? 
(Just adding a long press gesture recognizer to the grid cell doesn't work.)

**Comment by evadne** [comment]
Might need to set up gesture recognized prevention and add the long press
gesture recognizer to the grid view.  But it is a guess right now.

On 2012-08-28, at 5:00, miho notifications@github.com wrote:

Is there a way to distinguish between a long press (for showing a options
menu) and a short tap for a selection?
(Just adding a long press gesture recognizer to the grid cell doesn't work.)

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/issues/154.

**Comment by AlanQuatermain** [comment]
Yeah, that's how we do it at Kobo— we install a long-press recognizer and tell the selection recognizer to require the long-press to fail, IIRC.

On 2012-08-28, at 12:35 PM, Evadne Wu notifications@github.com wrote:

> Might need to set up gesture recognized prevention and add the long press 
> gesture recognizer to the grid view. But it is a guess right now. 
> 
> On 2012-08-28, at 5:00, miho notifications@github.com wrote: 
> 
> Is there a way to distinguish between a long press (for showing a options 
> menu) and a short tap for a selection? 
> (Just adding a long press gesture recognizer to the grid cell doesn't work.) 
> 
> — 
> Reply to this email directly or view it on 
> GitHubhttps://github.com/AlanQuatermain/AQGridView/issues/154.
> —
> Reply to this email directly or view it on GitHub.

Cheers,
-Jim

jimdovey@(mac|gmail).com
http://twitter.com/alanQuatermain
http://github.com/alanQuatermain
http://stackoverflow.com/users/103900/jim-dovey
http://ca.linkedin.com/pub/jim-dovey/2/24b/883

**Comment by hohl** [comment]
Thanks for the hints. I solved the problem by disabling selections with `self.gridView.allowsSelection = NO;` and adding my own gesture recognizers.

Kobo eBook Reader? Nice to hear, that this component is used by well known applications.
