### ISSUE TITLE
Defining a number of grid cell to be 'preloaded'

### ISSUE THREAD

**Issue by hohl** [AlanQuatermain/AQGridView#157]
In UITableView cell you can set a number of items which should be loaded even if they are not displayed. If you want make the scrolling more fluent you make this property value higher so more items are already in memory and scrolling is more fluent.

At the moment my grid view scrolling isn't very fluent with just an image and two labels on each cell. I would love to set the preload grid cells a bit higher.

**Comment by evadne** [comment]
This looks like an app design issue and should probably be handled at app
level.  Would you share how the table view pre-loads items?

On 2012-08-31, at 6:05, miho notifications@github.com wrote:

In UITableView cell you can set a number of items which should be loaded
even if they are not displayed. If you want make the scrolling more fluent
you make this property value higher so more items are already in memory and
scrolling is more fluent.

At the moment my grid view scrolling isn't very fluent with just an image
and two labels on each cell. I would love to set the preload grid cells a
bit higher.

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/issues/157.

**Comment by hohl** [comment]
You are right. I got it working by changing the way to load the image. (Problem was the UIImage got scaled when displayed)
