### ISSUE TITLE
enqueueReusableCells: doesn't

### ISSUE THREAD

**Issue by jdmuys** [AlanQuatermain/AQGridView#16]
In reloadData there is this call:

```
[self enqueueReusableCells: _visibleCells];
```

Inside which call there is this test:

```
- (void) enqueueReusableCells: (NSArray *) reusableCells
{
for ( AQGridViewCell * cell in reusableCells )
{
    if ( [_visibleCells containsObject: cell] )
    {
        NSLog( @"Warning: tried to add duplicate gridview cell" );
        continue;
    }
```

Clearly, this will be triggered every time. So we get a spurious warning. More problematic, the `continue` statement means that the cells will _not_ be enqueued.

Since I have not analyzed the whole flow, I am a bit nervous about removing the test altogether. Could you confirm that this test is simply inappropriate?

Regards,

Jean-Denis

**Comment by AlanQuatermain** [comment]
I thought I had removed this; maybe it got squashed in a merge somewhere— I'll take a look.

The actual comparison is supposed to be against the queued cells list, to see if we'd enqueued the same object twice (this was happening here for a while and was causing some weird shit to happen). Looks like either a typo or a merge squash to me.

**Comment by chriseidhof** [comment]
Just to let you know: I've encountered the same bug. I'm also not sure what the appropriate fix is, I did the following workaround:
    -       [self enqueueReusableCells: _visibleCells];
    -       [_visibleCells removeAllObjects];
    +    NSArray\* removeCells = [_visibleCells copy];
    +    [_visibleCells removeAllObjects];
    +       [self enqueueReusableCells: removeCells];

**Comment by AlanQuatermain** [comment]
I've fixed this in the latest commit. There's a bunch of other (mostly minor) adjustments to come from the Kobo project at some point, although we're still changing a couple things around so I don't have time to QA it just yet. This issue should be gone now though.
