### ISSUE TITLE
libAQGridView.a appearing in RED

### ISSUE THREAD

**Issue by KaushiKularatnam** [AlanQuatermain/AQGridView#161]
I am just setting this up and am on step 9 and when i add this it appears in red? WHY IS THAT?

**Comment by evadne** [comment]
No worries.  Run your app as usual.  Xcode quirk.  THANK YOU.
- *

On Sep 13, 2012, at 8:36, KaushiKularatnam notifications@github.com wrote:

I am just setting this up and am on step 9 and when i add this it appears
in red? WHY IS THAT?

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/issues/161.

**Comment by KaushiKularatnam** [comment]
Thanks.. Solved.. It did run initially but i wasn't sure if there would be future complications. Well if thats the case then im good to go. thanks agian
