### ISSUE TITLE
Can we add the project to a non-ARC project?

### ISSUE THREAD

**Issue by ghost** [AlanQuatermain/AQGridView#163]
I have been breaking my head on how to get it to work with a pin pad I'm trying to design. The project works wonders with an ARC version of my project, but when I try using it with my non-ARC version, even though it presents itself properly, any strings I am trying to preserve through my project that take the information from the grid view get released and it gives me a crash for attempting to call something on a deallocated string. Do you still support non-ARC projects?

**Comment by evadne** [comment]
It’s favorable that you add the project as a static library, instead of including the files directly.  The README on the develop branch outlines a possible approach that you might want to adopt.  If you add files directly to your app, it will easily break whenever AQGridView adds or removes private classes and you want to update.

**Comment by ghost** [comment]
Yeah, I actually added it as a static library following the directions. It adds it just fine. My issue is that it deallocates any information from the cells. To be more specific, the pin pad displays correctly, each cell has a button, I can read the tag for the button and anything related to it to include an assigned value. When I try to modify a retained string in my class that uses the grid view by calling any string method to it after the second time it throws a sending message to deallocated instance.

**Comment by evadne** [comment]
Would meekly and nicely argue that it is a design issue which can be solved by never storing any interaction-critical data in the cell (or view layer in general); without ARC, the approach mentioned likely would cause a memory leak.

A common approach is to strictly interact with information stored by your grid view data source and treat views as ephemeral.

In any case, would be glad to look at your code if you can make a reduced case.  There’s always a chance where the grid view is doing something funny and my assumptions are way off.

**Comment by ghost** [comment]
Yeah I can definitely show you. Honestly, any help at this point would be great. The one thing that baffles me is that the exact same project works perfectly if I convert it to ARC. Even with the design issue argument. All my class does is append to a string the value passed by the button in the cell. Like I said, it works awesomely if my project is converted to ARC, but not if I leave it un modified. The grid still works but the string methods on that retained string make it crash only in non-ARC project.

Like you said, it could be a design issue, it's task is very simple. All I'm mentioning on the issue is that it behaves different in ARC and non-ARC projects.

Allan Salcedo

**Comment by evadne** [comment]
Any updates?  Is the code up somewhere?

**Comment by evadne** [comment]
@ASalcedo I’ll be closing the issue for now since it has been two weeks.  If you happen to have a snippet that triggers the issue, feel free to post it somewhere and re-open the issue.  Thanks again for your report.

**Comment by ghost** [comment]
Well, the issue only gets solved when I convert my current non-ARC project to ARC. The only workaround I found was to use an NSMutableString as opposed to a regular NSString in the non-ARC version. As I mentioned before, the ARC version of my project works just fine with NSString.

**Comment by evadne** [comment]
Allan,

I need to see the code.  No code, no bug fix.
- *

On Oct 1, 2012, at 7:03, Allan Salcedo notifications@github.com wrote:

Well, the issue only gets solved when I convert my current non-ARC project
to ARC. The only workaround I found was to use an NSMutableString as
opposed to a regular NSString in the non-ARC version. As I mentioned
before, the ARC version of my project works just fine with NSString.

On Sep 28, 2012, at 9:18 PM, Evadne Wu notifications@github.com wrote:

> @ASalcedo I’ll be closing the issue for now since it has been two weeks.
> If you happen to have a snippet that triggers the issue, feel free to post
> it somewhere and re-open the issue. Thanks again for your report.
> 
> —
> Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/issues/163#issuecomment-9032927.
