### ISSUE TITLE
AQGridViewCell: make it a subclass of UITableViewCell instead?

### ISSUE THREAD

**Issue by jdmuys** [AlanQuatermain/AQGridView#17]
Hi,

Making AQGridViewCell a subclass of UITableViewCell would make it possible to use the Interface Builder Table View Cell standard item. Did you perhaps consider that idea and reject it? Is there some pitfall to take into account?

Conceptually, it makes quite a bit of sense also, as the two classes share a lot of behavior.

**Comment by AlanQuatermain** [comment]
UITableViewCell contains too much table-specific behaviour and data. I don't especially want to re-use that, and I don't want Apple to reject anything based on my working around private APIs in UITableView. I'd much rather redefine the lot.

IB support is on the roadmap, both for the cells and the grid view itself.
