### ISSUE TITLE
Possible to adjust cell offset

### ISSUE THREAD

**Issue by karmeye** [AlanQuatermain/AQGridView#175]
Is it possible to adjust each individual cell's position?

I have a shelf background, and the items are not properly aligned to the shelves. 
The cell items are of different sizes.

Thanks.

**Comment by AlanQuatermain** [comment]
Absolutely: implement the -(CGRect)gridView:adjustCellFrame:withinGridCellFrame: method in your AQGridViewDelegate. That is passed the CGRect for the cell's default frame along with the CHRect of the logical bounding box within which it is by default centered. Assuming your shelf sits N pixels above the bottom of the grid, you can just adjust the default frame so it's bottom sits N pixels above the bottom of the bounding box.

This is actually the exact same case for which the method was originally created: laying out books on the Kobo app's shelf view.

**Comment by karmeye** [comment]
Perfect! Thank you!

**Comment by karmeye** [comment]
Is there support for different sizes of cellFrames?
When I adjust the cellFrame according to the cell image size the spring board example stops working when moving cells.
