### ISSUE TITLE
AQGridViewCell reuseIdentifier property should not be read-only

### ISSUE THREAD

**Issue by jdmuys** [AlanQuatermain/AQGridView#19]
Since it's not possible to set the identifier of the cell in Interface Builder, it has to be initialized in `awakeFromNib`. However this is not possible since the `reuseIdentifier` property is declared read-only in the `@interface`. This prevents me from doing the following in my cell subclass:

```
- (void)awakeFromNib {
    [super awakeFromNib];
    self.reuseIdentifier = @"CellIdentifier";
}
```

Note that this property is privately redeclared read-write in the implementation file, which lets `AQGridViewCell` do it in its initialization routines:

```
    self.reuseIdentifier = reuseIdentifier;
```

Of course, I can still do (and indeed I _must_ do):

```
    _reuseIdentifier = @"CellIdentifier";
```

But that kind of defeats the idea of a property.

Of course, if `AQGridViewCell` was a subclass of `UITableViewCell`, this would be moot as I could set the identifier in IB.

**Comment by AlanQuatermain** [comment]
Feel free to pretend it's read-write, or to redefine it in the header file (or your subclass's implementation file) for your purposes. Proper IB support is on the roadmap, but not very close right now as I have other priorities. That would be preferable to any attempt to make it piggy-back on UITableViewCell, which implements a lot of UITableView-specific stuff— trust me, I'm a reverse-engineer ;o)

**Comment by jdmuys** [comment]
I trust you :-)
Thanks for your time.

**Comment by evadne** [comment]
Closing as resolved.

**Comment by yuzhouwww** [comment]
Thanks for your brilliant working.I want to know how you resolved this issue,i saw the property reuseidentifer is still readonly.

**Comment by evadne** [comment]
Just change the ivar or use Key-Value Coding which does access the ivar for
you.
- *

On Jun 29, 2013, at 6:12, yuzhou notifications@github.com wrote:

Thank for your brilliant working.I want to know how you resolved this
issue,i saw the property reuseidentifer is still readonly.

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/issues/19#issuecomment-20229551
.

**Comment by yuzhouwww** [comment]
Thanks for your time.I added a contentView in XIB and changed the ivar _reuseIdentifier,it worked.
