### ISSUE TITLE
libobjc.A.dylib`objc_msgSend:

### ISSUE THREAD

**Issue by vincekruger** [AlanQuatermain/AQGridView#190]
If i change my Deployment Target for 5.0 this all works fine, but on 6.0 and 6.1 there is this error.  Why is that? What am I doing wrong?

**Comment by evadne** [comment]
Can you provide more detail?
- *

On Feb 19, 2013, at 1:47, Vince Kruger notifications@github.com wrote:

If i change my Deployment Target for 5.0 this all works fine, but on 6.0
and 6.1 there is this error. Why is that? What am I doing wrong?

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/issues/190.

**Comment by vincekruger** [comment]
When I try and run my app in the simulator with a 6.1 target if these errors

---

libobjc.A.dylib`objc_msgSend:
0x15fd08c:  movl   8(%esp), %ecx
0x15fd090:  movl   4(%esp), %eax
0x15fd094:  testl  %eax, %eax
0x15fd096:  je     0x15fd0e8                 ; objc_msgSend + 92
0x15fd098:  movl   (%eax), %edx
0x15fd09a:  pushl  %edi
0x15fd09b:  movl   8(%edx), %edi
0x15fd09e:  pushl  %esi
0x15fd09f:  movl   (%edi), %esi
0x15fd0a1:  movl   %ecx, %edx
0x15fd0a3:  shrl   $2, %edx

## 0x15fd0a6:  andl   %esi, %edx (Thread 1: Breakpoint 3.1)

![Uploading Screen Shot 2013-02-19 at 11.50.26 AM.png . . .]()
StoreViewController.h

```
#import <UIKit/UIKit.h>
#import "AQGridView.h"

@interface StoreViewController : UIViewController <AQGridViewDelegate, AQGridViewDataSource>

@property (nonatomic, retain) IBOutlet AQGridView* gridView;
@property (nonatomic, retain) NSArray* services;

@end
```

StoreViewController.m

```
#import "StoreViewController.h"
#import "StoreGridViewCell.h"

@implementation StoreViewController

@synthesize gridView, services;

-(void)viewDidLoad
{
    [super viewDidLoad];

    self.gridView = [[AQGridView alloc] initWithFrame:CGRectMake(0, 0, 500, 400)];
        self.gridView.autoresizingMask = UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;
        self.gridView.autoresizesSubviews = YES;
        self.gridView.delegate = self;
        self.gridView.dataSource = self;

    [self.view addSubview:gridView];
    [self.gridView reloadData];
}

# pragma mark - GridView Implentation

-(NSUInteger)numberOfItemsInGridView:(AQGridView *)aGridView
{
    return 6;
}

-(AQGridViewCell *)gridView:(AQGridView *)aGridView cellForItemAtIndex:(NSUInteger)index
{
    static NSString *PlainCellIdentifier = @"PlainCellIdentifier";
    StoreGridViewCell *cell = (StoreGridViewCell *)[aGridView dequeueReusableCellWithIdentifier:@"PlainCellIdentifier"];

    if(cell == nil)
    {
        cell = [[StoreGridViewCell alloc] initWithFrame: CGRectMake(0.0, 0.0, 300, 123)
                                        reuseIdentifier: PlainCellIdentifier];
    }

    [cell.imageView setImage:[UIImage imageNamed:@"service-2.jpg"]];
    [cell.captionLabel setText:@"Sample service"];

    return cell;
}

@end
```
