### ISSUE TITLE
Crash while dragging and/or scrolling

### ISSUE THREAD

**Issue by whynoceros** [AlanQuatermain/AQGridView#191]
I have implemented a simple instance of AQGridView, which displays one column of custom cells. Whenever I attempt to scroll up or down, I get a crash and the only "usable" info in the crash is (full screenshot below):

-[UIScrollView(UIScrollViewInternal) _scrollViewWillBeginDragging] + 171

![Screen Shot 2013-03-07 at 1 29 57 PM](https://f.cloud.github.com/assets/1585185/234262/51cd2b90-876e-11e2-82ce-11560f2353ac.png)

**Comment by Irfanputitout** [comment]
Any help regarding this issue ? I am facing same crash.
