### ISSUE TITLE
asynchronous image loading problem

### ISSUE THREAD

**Issue by migfabio** [AlanQuatermain/AQGridView#197]
I use this code for download image asynchronous. The download is successful and I get a picture, but does not appear in the grid. What could be wrong?
- (AQGridViewCell *)gridView: (AQGridView *) aGridView cellForItemAtIndex: (NSUInteger) index {
  static NSString \* cellIdentifier = @"CustomCellIdentifier";
  
  AQGridViewCell \* cell = nil;
  CustomCell *customCell = (ModelliCell *)[aGridView dequeueReusableCellWithIdentifier:cellIdentifier];
  if (customCell == nil) {
      customCell = [[ModelliCell alloc] initWithFrame: CGRectMake(0.0, 0.0, 800.0, 150.0)
                                                      reuseIdentifier:cellIdentifier];
      customCell.selectionStyle = AQGridViewCellSelectionStyleGray;
  }
  MyObject *obj = [myArrayOfObjs objectAtIndex:index];
  customCell.title = obj.description;
  if ([obj.arrayOfImages count] > 0) {
      customCell.image = [obj.arrayOfImages objectAtIndex:0];
  } else {
      [self startDownloadImageForIndex:index];
  }
  
  cell = customCell;
  return cell;
  }

---
- (void)startDownloadImageForIndex:(NSUInteger)index {
  MyObject *obj = [myArrayOfObjs objectAtIndex:index];
  
  NSURL *url = myurl.....;
  
  NSURLRequest *request = [NSURLRequest requestWithURL:url
                                           cachePolicy:NSURLRequestUseProtocolCachePolicy
                                       timeoutInterval:10];
  
  [NSURLConnection sendAsynchronousRequest:request
                                     queue:[[NSOperationQueue alloc] init]
                         completionHandler:^(NSURLResponse *response, NSData *data, NSError *error)
   {
  
  ```
   if ([data length] >0 && error == nil)
   {
       dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
           NSError *error;
           NSDictionary* json = [NSJSONSerialization
                                    JSONObjectWithData:data
                                    options:kNilOptions
                                    error:&errorImg];
  
           if (error == nil) {
               NSArray *images = [jsonImg objectForKey:@"images"];
               for (NSDictionary *image in images) {                         
                   UIImage *imageLoaded = [UIImage imageWithData:[NSData dataFromBase64String:[image objectForKey:@"base64raw"]]];
                   [obj.arrayOfImages addObject:imageLoaded];
               }
           }
           dispatch_async(dispatch_get_main_queue(), ^{
               if ([obj.arrayOfImages count] > 0) {
                   CustomCell *customCell = (CustomCell *)[self.gridView cellForItemAtIndex:index];
                   customCell.image = [obj.arrayOfImages objectAtIndex:0];
                   [self.gridView setNeedsDisplay];
               }
  
           });
       });
   }
   else if ([data length] == 0 && error == nil)
   {
       NSLog(@"Nothing was downloaded.");
   }
   else if (error != nil){
       NSLog(@"Error = %@", error);
   }
  ```
  
   }];
  }

**Comment by mishuvolan** [comment]
you can try using this example http://gregprice.co.uk/blog/?p=36

**Comment by migfabio** [comment]
I solved in this way:
- (AQGridViewCell *)gridView: (AQGridView *) aGridView cellForItemAtIndex: (NSUInteger) index {
  static NSString \* cellIdentifier = @"CustomCellIdentifier";
  
  AQGridViewCell \* cell = nil;
  CustomCell \* customCell = (CustomCell *)[aGridView dequeueReusableCellWithIdentifier:cellIdentifier];
  if (customCell == nil) {
      customCell = [[CustomCell alloc] initWithFrame: CGRectMake(0.0, 0.0, 800.0, 150.0)
                                                      reuseIdentifier:cellIdentifier];
      customCell.selectionStyle = AQGridViewCellSelectionStyleGray;
  }
  MyObject *obj = [myArrayOfObjs objectAtIndex:index];
  customCell.title = obj.description;
  customCell.image = nil;
  
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
      if ([obj.arrayOfImages count] == 0) {
          [self startDownloadImageForObject:obj];
      }
      dispatch_async(dispatch_get_main_queue(), ^{
          CustomCell *updateCell = (CustomCell *)[self.gridView cellForItemAtIndex:index];
          if (updateCell) {
              if ([obj.arrayOfImages count] > 0) {
                  updateCell.image = [obj.arrayOfImages objectAtIndex:0];
              } else {
                  updateCell.image = nil;
              }
              [updateCell.contentView setNeedsLayout];
          }
      });
  });
  cell = customCell;
  return cell;
  }

---
- (void)startDownloadImageForObject:(MyObject *)obj {
  NSURL *url = obj.urlImages;
  NSURLRequest *request = [NSURLRequest requestWithURL:url
                                           cachePolicy:NSURLRequestReloadIgnoringCacheData
                                       timeoutInterval:10];
  
  NSURLResponse \* response = nil;
  NSError \* error = nil;
  NSData \* data = [NSURLConnection sendSynchronousRequest:request
                                        returningResponse:&response
                                                    error:&error];
  
  if (error == nil)
  {
      NSError _errorImg;
      NSDictionary_ jsonImg = [NSJSONSerialization
                               JSONObjectWithData:data
                               options:kNilOptions
                               error:&errorImg];
  
  ```
  if (errorImg == nil) {
      NSArray *images = [jsonImg objectForKey:@"images"];
      for (NSDictionary *image in images) {
          UIImage *imageLoaded = [UIImage imageWithData:[NSData dataFromBase64String:[image objectForKey:@"image"]]];
          [obj.arrayOfImages addObject:imageLoaded];
      }
  }
  ```
  
  }
  }
