### ISSUE TITLE
Lines not drawn correctly when rotating

### ISSUE THREAD

**Issue by funkyboy** [AlanQuatermain/AQGridView#21]
I run the app in portrait mode. Works fine.
  http://www.studiomagnolia.it/tmp/photo1.PNG
I rotate and the last line of the last cell is not drawn
  http://www.studiomagnolia.it/tmp/photo2.PNG

If you do the opposite (first landscape and then portrait) almost the same happens. One line is not dranw.
I verified the same behavior in your ImageDemo example.

**Comment by funkyboy** [comment]
Hi, any news about this issue?
Any hint about the piece of code to inspect?

**Comment by AlanQuatermain** [comment]
Sorry for the late response.

You want to look at the -delegateWillDisplayCell:atIndex: method right at the bottom of AQGridView.m; that's where it decides which separators need to be drawn.

**Comment by evadne** [comment]
Closing as invalid (original images missing, no correspondence).  Feel free to re-open this issue. :)
