### ISSUE TITLE
bounce = YES does not work properly

### ISSUE THREAD

**Issue by ghost** [AlanQuatermain/AQGridView#23]
UIScrollView usually has bounce ability by setting the property. I've tried this:

AQGridView \* contentView = [[AQGridView new] autorelease];
    contentView.backgroundColor = [UIColor whiteColor];
    contentView.autoresizingMask = UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;
    contentView.autoresizesSubviews = YES;
    contentView.delegate = self;
    contentView.dataSource = self;
    contentView.resizesCellWidthToFit = NO;

```
    contentView.bounces = YES;
contentView.alwaysBounceVertical = YES;
contentView.alwaysBounceHorizontal = YES;
```
## 

but nothing happens with Bouncing, seems like it does not work...

**Comment by blackgold9** [comment]
I'm seeing this always. Did it ever work?

**Comment by ghost** [comment]
Oh, it was long ago...

I've spend some time long ago and now it works fine for me (but I don't remember actual fix -- it was kind of easy I suppose)
Mostlikely, I did not modify the code of AQGridView, but not sure...

I did not close the issue, sorry,... guilty...
