### ISSUE TITLE
Custom cell with TTImageView

### ISSUE THREAD

**Issue by traustitj** [AlanQuatermain/AQGridView#26]
I created my own cell which only contains ImageView.  By using the UIImageView everything works as expected, but by just changing the UIImageView to TTImageView everything actually works except I am unable to pick a cell.  When I click on a cell it does not get chosen.  

Anyone with any ideas ?

**Comment by wader** [comment]
Maybe your view (or some subview) has userInteractionEnabled set to YES and does not propagate the event?
