### ISSUE TITLE
AQGridView license

### ISSUE THREAD

**Issue by luismmontielg** [AlanQuatermain/AQGridView#27]
Hello, 
Can I use this on a commercial app?

**Comment by luismmontielg** [comment]
do I have to pay anything?

**Comment by AlanQuatermain** [comment]
It's licensed under the New BSD license, so you're free to use it in any project, commercial or noncommercial, so long as you include the copyright disclaimer from the project's LICENSE file somewhere in your application. This can be either within the application itself on an 'about' screen, or as part of a custom end user license agreement.
