### ISSUE TITLE
App crashes when deleting last gridviewCell in row

### ISSUE THREAD

**Issue by dasnovum** [AlanQuatermain/AQGridView#28]
After deleting the last cell in row, the app crashes with the following NSRangeException.

<code>

**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[NSCFArray objectsAtIndexes:]: the last index (19) must be less than the count (19).'
2010-11-10 10:01:12.900 SpringBoard[2038:207] Stack: (
    43575376,
    44733228,
    43312907,
    43312746,
    810502,
    46066,
    28950,
    41543958,
    41543205,
    41486802,
    41486130,
    41686758,
    43063890,
    42853189,
    42850472,
    52562077,
    52562274,
    3117938,
    9456,
    9310
)
terminate called after throwing an instance of 'NSException'
</code>

**Comment by phaus** [comment]
Added some lines to remove invalid indices before updating the gridview:

In AQGridView:

1437a1438,1446

> ```
>           NSUInteger index=[shifted firstIndex];
>           while(index != NSNotFound){
>               NSLog(@"%i >= %i ?", index, [_visibleCells count]);
>               if (index >= [_visibleCells count]) {
>                   [shifted removeIndex:index];
>               }                   
>               index=[shifted indexGreaterThanIndex: index];
>           }
> ```
> 
> 2069c2078
> < @end
> 
> ## \ No newline at end of file
> 
> @end

**Comment by dasnovum** [comment]
seems to fix the problem :-) thanks!
