### ISSUE TITLE
AQGridView as Static Library

### ISSUE THREAD

**Issue by kfarst** [AlanQuatermain/AQGridView#32]
Added the project into the Frameworks folder, made it a Direct Dependency in the app, as well as added the path for AQGridView to the Header Search Paths and User Header Search Paths. Added '-ObjC' and '-all_load' to Other Linker Flags since it is a 4.0 project. What else am I missing?

**Comment by markph0204** [comment]
What error are you getting kfarst?

**Comment by kfarst** [comment]
warning: skipping file '/Users/kfarst/projects/PivotPoint/Libraries/AQGridView.xcodeproj' (unexpected file type 'wrapper.pb-project' in Link Binary with Libraries build phase)

**Comment by AlanQuatermain** [comment]
I've never even bothered with that. All the classes are inside the root 'Classes' folder, so I just drag those files directly into the other projects and either copy or reference them.  The example projects all just include the raw .m and .h files as references.

Alternatively you can simply build the static library separately and include that by reference along with just the header files from the AQGridView project.

**Comment by markph0204** [comment]
First, I did what Alan suggests, which works.
Next, I made a static library Framework.  Alan would you be interested in adding that in? If so I can fork/request pull.  Its a simple bash script that could be dropped into the scripts directory, plus an umbrella header for easy import of common headers.

**Comment by AlanQuatermain** [comment]
Sure, that sounds pretty useful.

**Comment by kfarst** [comment]
Thank you both for your help!
