### ISSUE TITLE
App crashes when deleting last grid view cell

### ISSUE THREAD

**Issue by coryroloff** [AlanQuatermain/AQGridView#5]
When calling the method "deleteItemsAtIndices:(NSIndexSet *)indices withAnimation:(AQGridViewItemAnimation)animation;" in AQGridView.h on the very last cell in the grid, the app crashes with the following errors:

Assertion failure in -[AQGridView fixCellsFromAnimation], AQGridView.m:788

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'visible cell count after animation (17) doesn't match visible indices (18)'

I verified that the code is attempting to delete the proper index, and that it returns the correct number of cells after a cell is deleted.

Note that calling this method on any cell other than the very last one works as intended. Please let me know if you need more information.

Thanks!

**Comment by DouweM** [comment]
The same thing seems to occur when inserting an item at the end of the `gridView`...
 I'm using an `NSFetchedResultsController` so inside `controller:didChangeObject:atIndexPath:forChangeType:newIndexPath:` I have this:

```
case NSFetchedResultsChangeInsert:
    [self.gridView insertItemsAtIndices:[NSIndexSet indexSetWithIndex:newIndexPath.row]                                    withAnimation:AQGridViewItemAnimationFade];
    break;
```

When adding an item to the end of the `gridView`, I am given this error:

```
Assertion failure in -[AQGridView fixCellsFromAnimation], AQGridView.m:788
CoreAnimation: ignoring exception: visible cell count after animation (6) doesn't match visible indices (7)
```

The app doesn't crash however, it keeps running with incorrect information backing the `gridView`. The effect this has is that the `gridView` is screwed up visually: some items are overlapping others, and there are empty spaces when rotating to landscape; also, when selecting one item, another item (the one next to the tapped one) is selected and when tapping the added item (it is visible!) this exception is thrown:

```
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[_PFBatchFaultingArray objectAtIndex:]: index (940903412) beyond bounds (6)'
```

One little thing that might or very well might not be related: It appears that `gridView:cellForItemAtIndex:` is called twice for the just added item...

**Comment by DouweM** [comment]
Huh, it looks like this happens when adding an item in the middle of the `gridView` too...
This is what I see:

```
My own NSLog inside gridView:cellForItemAtIndex:
Visible cell list is missing some items!
Got 1 missing indices
My own NSLog inside gridView:cellForItemAtIndex:
*** Assertion failure in -[AQGridView fixCellsFromAnimation], AQGridView.m:788
CoreAnimation: ignoring exception: visible cell count after animation (6) doesn't match visible indices (7)
```

When adding an item to the beginning of the `gridView`, I see no Assertion failure, but I do see this:

```
My own NSLog inside gridView:cellForItemAtIndex:
Visible cell list is missing some items!
Got 1 missing indices
My own NSLog inside gridView:cellForItemAtIndex:
```

**Comment by DouweM** [comment]
Wow, this is getting weirder and weirder (for my non-Cocoa genius mind at least)...

I use this code to load some data into my Core Data store, as the app's still in very early beta, and adding data via the app doesn't work yet:

```
    NSManagedObjectContext *managedObjectContext = self.fetchedResultsController.managedObjectContext;

NSManagedObject *languagePair = [managedObjectContext insertNewEntityWithName:@"LanguagePair"];

[languagePair setValue:@"English" forKey:@"foreignLanguage"];
[languagePair setValue:@"Dutch" forKey:@"ownLanguage"];
[languagePair setValue:[NSNumber numberWithInt:1] forKey:@"displayOrder"];

languagePair = [managedObjectContext insertNewEntityWithName:@"LanguagePair"];

[languagePair setValue:@"German" forKey:@"foreignLanguage"];
[languagePair setValue:@"Dutch" forKey:@"ownLanguage"];
[languagePair setValue:[NSNumber numberWithInt:2] forKey:@"displayOrder"];

NSError *error;
if (![managedObjectContext save:&error]) {
    NSLog(@"%@", [error localizedDescription]);
}
```

(`insertNewEntityWithName:` is in a category on `NSManagedObjectContext`, as a proxy for `NSEntityDescription`'s `insertNewObjectForEntityForName:inManagedObjectContext`)

This gives me this:

```
ChangeInsert: <NSIndexPath 0x15a400> 2 indexes [0, 0]
ChangeInsert: <NSIndexPath 0x15a450> 2 indexes [0, 1]
Loading cell for German
Program received signal:  “EXC_BAD_ACCESS”.
```

The first two are my own `NSLog`s in `NSFetchedResultsController`'s `controller:didChangeObject:atIndexPath:forChangeType:newIndexPath:`, with the type of change, and the provided `NSIndexPath`. The third is also one of my `NSLog`s, one in `gridView:cellForItemAtIndex:`, with the `NSManagedObject`'s `foreignLanguage`.
The `EXC_BAD_ACCESS` happens on `AQGridViewUpdateInfo.m:775`.

At this point I'm not sure anymore if these are problems with your code or mine (as these are a LOT of problems), but my `NSFetchedResultsController` handling seems to be fine...

If you need any more of my code to figure out what the heck is going wrong, please say so.

**Comment by DouweM** [comment]
After a lot of stepping through the code managing the animation for inserting an item, it looks like on line 776 of `AQGridViewUpdateInfo.m` (`[newVisibleCells addObject: item];`), `item` isn't added to the `newVisibleCells` `NSMutableSet`, causing `newVisibleCells` to have a `count` `1` lower than it should be, causing the assertion on line 788 of `AQGridView.m` (`NSAssert2([newVisibleCells count] == _visibleIndices.length, ...)`) to fail, causing the code after this failed assertion not to fire.
Why `newVisibleCells` would not 'accept' `item`, I don't know however...

**Comment by DouweM** [comment]
After more stepping through the code, it seems that on line 769 of `AQGridViewUpdateInfo.m` `item` still contains the `AQGridViewUpdateItem` from the fast enumeration, as expected, but on line 772, `item` now points to `0x0`, which I guess is `nil`, so `item.animation` and `item.index`both return `0`. 
Thus, the `AQGridViewAnimatorItem` is `init`'d with an `index` of `0`, and as an object with `index == 0` already exists in the `newVisibleCells` `NSSet`, `item` is not added to it, causing the problems I described above.

**Comment by DouweM** [comment]
Yay, another weird crash with a really unhelpful call stack:
![Call stack](http://cl.ly/48eae0042b15080f6581/content)

Stepping through the code, it looks like the `objc_msgSend` fail happens on line 775 of `AQGridViewUpdateInfo.m`, which reads `AQGridViewAnimatorItem * item = [AQGridViewAnimatorItem itemWithView: cell index: item.index];`. 
When I choose Jump over or Jump into while on this line, the application crashes, without actually going into `itemWithView:index:`.
This happens when I try to add a first item to the `gridView` (by adding a first `NSManagedObject` to the `NSManagedObjectContext`)

**Comment by AlanQuatermain** [comment]
Is this still happening after last week's code dump? I certainly don't see it in the Kobo application, but there may be a little difference between our NSFetchedResultsController integration.

**Comment by DouweM** [comment]
Let's hope it's fixed then :) Will check the big update out when I get home.

**Comment by DouweM** [comment]
Yup, fixed! Thanks :D

**Comment by AlanQuatermain** [comment]
Sweet :o)
