### ISSUE TITLE
AQGridView memory leak

### ISSUE THREAD

**Issue by andyzaharia** [AlanQuatermain/AQGridView#55]
I'm having some really weird memory leaks in my code, which seems to be caused by the AQGridViewCell contentView method, basically it looks like the _contentView object is not getting released, here is the Instruments screen shot http://andyzaharia.com/instruments_screenshot.png 

And here is the source code where it happens http://andyzaharia.com/leaks.zip

I just spent an entire day trying to figure out why this happens and no luck so far, anyone can help ? :)

Thanks a lot, and thank you for this wonderful grid view !

**Comment by darrylhthomas** [comment]
I believe I've encountered the same leak. I'm about to send a pull request with my fix.

**Comment by evadne** [comment]
Closing as _believed to be_ invalid (project now uses ARC).  Feel free to re-open this issue. :)
