### ISSUE TITLE
gridView:cellForItemAtIndex: never called

### ISSUE THREAD

**Issue by tonyarnold** [AlanQuatermain/AQGridView#56]
Hi Alan,

Thanks for the great code!

I've been trying to implement AQGridView against an NSFetchedResultsController for about an hour now without much luck. It seems that `numberOfItemsInGridView:` is called as expected (and returns an integer greater than 0), but `gridView:cellForItemAtIndex:` is never called.

I set the delegate and datasource to the current instance, but it never seems to do anything. I'm happy to provide any information, but I'll have to obfuscate some of the details in my code if that's required.

**Comment by AlanQuatermain** [comment]
The first thing I'd do is to make sure that the grid view has a non-zero frame rectangle. I had the exact same issue a while back, and it was because some auto-resizing wasn't kicking in and my grid view's frame was (0,0,0,0).

**Comment by tonyarnold** [comment]
Thanks mate — it was a combination of that, and having the AQGridView instance be the view controller's view as well (rather than being a subview of a standard UIView). Once I did that, it all started working — how very odd!

Thanks for your prompt help — it was very much appreciated!

**Comment by realalien** [comment]
Thanks and I'd like to share some hints, hope it helps for someone has the similar problem ("gridView:cellForItemAtIndex: is never called"). 

It is easily forgotten that a gridview IBOutlet property of the viewController be hooked up with a Grid View UI, manually create connection in the Interface Builder.

**Comment by ftedin** [comment]
Thaaaank you, realalien! in my case the use was that the AQGridView was included in the main View, then datasource was not working, you saved my day!
