### ISSUE TITLE
Memory leak in AQGridViewUpdateInfo.m

### ISSUE THREAD

**Issue by rbritton** [AlanQuatermain/AQGridView#6]
As of commit 672a56df63baf443c5bc74ae235ea960073d6442, there is a leaked CFMutableDictionaryRef created on line 647 (animatingCellTable).  It's created but never released.

**Comment by AlanQuatermain** [comment]
Thanks, I've made that change now. There are a couple of other changes I need to merge that the guys here at Kobo made, so if it's not there already please bear with me, it'll be in soon.
