### ISSUE TITLE
reload data does not update cells

### ISSUE THREAD

**Issue by bhatti** [AlanQuatermain/AQGridView#7]
I am testing AQGridView, where I load different data based on the filter defined and it's not updating cells when I call reloadData and still displays same cells. Just looking at the code, there seems to be a problem with animation as updateVisibleGridCellsNow method finds _animationCount > 0 and returns without updating the view. Please help.

**Comment by AlanQuatermain** [comment]
I'll have to take a look at this, but there have been some fiddly changes made to AQGridView here over the last week, and it may be fixed by that. I'll post more when I find out what's happening.

**Comment by AlanQuatermain** [comment]
This should be fixed after last week's code dump from Kobo. Let me know if it's still happening, otherwise I'll close this bug soon.

**Comment by woutergoossens** [comment]
I also have this problem when I want to update the gridview with reloaddata

Warning: tried to add duplicate gridview cell

Do you have any solution yet?

**Comment by shizam** [comment]
Also have a similar issue re: 'Warning: tried to add duplicate gridview cell' which seems to stem from this problem:

AQGridView:reloadData
    [_visibleCells makeObjectsPerformSelector:@selector(removeFromSuperview)];
    [self enqueueReusableCells: _visibleCells];
    [_visibleCells removeAllObjects];

AQGridView:enqueueReusableCells
    if ( [_visibleCells containsObject: cell] ) {
        NSLog( @"Warning: tried to add duplicate gridview cell" );
        continue;
    }

Notice that reloadData calls 'enqueueReusableCells' before asking visibleCells to removeAllObjects but w/in 'enqueueReusableCells' it checks if visibleCells contains the cells (which it still does at this point) and throws the warning.

So it never actually enqueues the cell for reuse and it gets released, it looks like every time you reloadData it has to recreate cells...

**Comment by AlanQuatermain** [comment]
The issue with the warning you mention has been fixed in the latest commit, so you shouldn't see this issue any more.
