### ISSUE TITLE
Unable to call AQGridViewDataSource tasks

### ISSUE THREAD

**Issue by adsahay** [AlanQuatermain/AQGridView#72]
This could possibly be a duplicate of [issue 56](https://github.com/AlanQuatermain/AQGridView/issues/56) but the remedies listed there don't work.

I'm using AQGridView as a subview hooked up via IBOutlet. The grid has the correct frame in `viewDidLoad` (same as the geometry defined in the interface builder). The dataSource and delegate properties are correctly set. However, none of the dataSource functions are being called. 

Can you help me debug this? What other members of the gridview should I check to see if something is nil or zero?

**Comment by AlanQuatermain** [comment]
First thing to check: are you calling -reloadData in your -viewDidLoad method?

**Comment by adsahay** [comment]
`reloadData` works. I guess this is a good candidate for documenting under differences with UITableView?
