### ISSUE TITLE
Select previously de-selected item

### ISSUE THREAD

**Issue by adsahay** [AlanQuatermain/AQGridView#73]
I'm building a video app where the grid shows thumbnails w/ titles. The user can tap to select/deselect videos, and all selected videos are pushed to a queue which can be then played.

In AQGridView - this is the observed behavior (in simulator):
- Selecting an item deselects previously selected item.
- Once an item is deselected in the above fashion, `didSelectItemAtIndex` for it is never called again, i.e., user is unable to select that item again.

What is a good way to modify the second behaviour? Is that a feature or a bug?

The first behaviour is well suited for selecting a single item at a time, but I want multiple items to be selected, any tips on how to deal with this? I could possibly store my own flag in my custom grid cell and monitor only selection events, ignore the "deselect".

**Comment by RuiAAPeres** [comment]
I get the same issue: unable to seleect that item again. Have you figured a way of fixing it?

**Comment by adsahay** [comment]
Sorry I didn't get this in my inbox!

I've written my own handling for selection to work around this. I've set selection to `AQGridViewSelectionNone`, and then overridden `willSelectItemAtIndex`, `didSelectItemAtIndex`, `willDeSelectItemAtIndex` and `didDeSelectItemAtIndex`.

The idea is to keep track of the selected item in a property, say, `selectedIndex`, and use it to show the selected or deselected version of your grid item. Hope this helps.
