### ISSUE TITLE
Bug: forced scrolling behavior?

### ISSUE THREAD

**Issue by mattaronoff** [AlanQuatermain/AQGridView#76]
There was a change committed here:
https://github.com/AlanQuatermain/AQGridView/commit/1e4fe3d0b6a4cb768544d3b4880d07f3ef7deafb

to allow "contents to be always scrollable." I believe that this is a bug. I certainly don't want the grid view to bounce when there aren't more items than space to display them. This setting should respect the "always bounces" option in UIScrollView, not simply be hard-coded to incorrectly calculate the content size. Thanks!

**Comment by pip8786** [comment]
This issue is causing my grid view to scroll vertically when it shouldn't as well.

**Comment by evadne** [comment]
I think the commit [was wrongfully merged](https://github.com/AlanQuatermain/AQGridView/commit/1e4fe3d0b6a4cb768544d3b4880d07f3ef7deafb) and the best thing to do is to remove that line on `master`.
