### ISSUE TITLE
updateVisibleGridCellsNow crash

### ISSUE THREAD

**Issue by ghost** [AlanQuatermain/AQGridView#77]
In iOS5, when `updateVisibleGridCellsNow` is called, the line:

```
removedIndices = [[[currentVisibleIndices aq_indexesOutsideIndexSet: newVisibleIndices] mutableCopy] autorelease];
```

throws the following exception:

```
2011-06-27 21:44:06.008 transfix[86427:207] -[NSIndexSet aq_indexesOutsideIndexSet:]: unrecognized selector sent to instance 0x810b5f0
2011-06-27 21:44:06.008 transfix[86427:207] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSIndexSet aq_indexesOutsideIndexSet:]: unrecognized selector sent to instance 0x810b5f0'
*** First throw call stack:
(0x13f7f1c 0x158a52e 0x13faa6b 0x1352076 0x1351bb2 0x103e1 0xa5e6 0x23f122 0x1150d7 0x11fa70 0xa7cd7 0xa9512 0xa9735 0x13c73ad 0x1356d47 0x13210e7 0x1320750 0x1320671 0x23790c3 0x2379188 0x200c29 0x22e9 0x2255)
```

**Comment by AlanQuatermain** [comment]
You need to include 'NSIndexSet+AQIndexesOutsideSet.{h|m}' in your project to get that method. They're inside the Classes folder with the main AQGridView classes.

**Comment by ghost** [comment]
Sorry, quite obvious in hindsight.

**Comment by marcwickens** [comment]
For anyone having this problem when linking as a static library, add the compiler flag "-all_load" 

See http://stackoverflow.com/questions/6034283/unrecognized-selector-sent-to-instance-to-a-static-library-despite-objc-flag

Had me pulling my hair out!

**Comment by zakdances** [comment]
The "-all_load" compiler flag should be mentioned in the project details somewhere...just spent 6 hours trying to debug this issue :(    (the -all_load flag finally fixed it)
