### ISSUE TITLE
AQGridView does not handle translucent nav bar correctly

### ISSUE THREAD

**Issue by luciuskwok** [AlanQuatermain/AQGridView#8]
If you put an AQGridView in an AQGridViewController with a black translucent navigation bar, the view should be laid out so that it extends underneath the nav bar, and have a negative contentOffset.y value to show a blank area which is shown under the nav bar when scrolled to the top. This situation is not being accounted for in the layout code.

**Comment by AlanQuatermain** [comment]
I'm not sure how I'm supposed to detect that I have to handle that in code— the only way I know off the top of my head involves watching the view hierarchy, but that would mean checking for private classes (i.e. UITransitionView). I'd always assumed that this was something which was done for me by the navigation controller.

**Comment by luciuskwok** [comment]
When I stepped through the code, I noticed that the contentOffset of the AQGridView was set to {0, -44} when in portrait mode with a translucent nav bar. I believe it's set to {0, -38} in landscape because the nav bar is shorter in landscape. There's two changes that fix this issue. One is in AQGridView, there are two places where instead of using CGPointEqualToPoint() to compare to CGPointZero, compare point.y <= 0.0f. 

The second change has to do with the way the content size is calculated. I turned off contentSizeGrowsToFillBounds but it was still expanding the content size to the bounds, and it also wasn't taking into account the negative content offset. As I was stepping through the code I noticed that in AQGridViewData, in sizeForEntireGrid, it sets the height of the grid to the height of the bounds, without checking if the flag that I set to no. So deleted the two lines with if statement that sets height = _gridView.bounds.size.height. 

In -[AQGridView setContentSze:] it looks like it should take into account a negative content offset when calculating the size to fill the bounds.

I'm not sure if I should make a fork with the changes or if it'll be easier if you make them yourself.

**Comment by AlanQuatermain** [comment]
Thanks Lucius.

Feel free to make a fork and update the code; it looks like it might be a couple more days before I can get back onto it myself.

**Comment by luciuskwok** [comment]
I found a lot more bugs with using it with a black translucent nav bar, related to the assumption that the contentOffset would be non-negative. I don't have time now to go through and fix it so I don't have a fork.

**Comment by evadne** [comment]
I don’t think we must support an initial negative content offset, although the code not working correctly under this case is a bug; here are a few solutions that will probably work:
- Wrap the entire grid view in another view, with a 44-pixel space between the grid view’s top margin and the enclosing view’s top margin
- Increase the top content inset of the grid view (it’s a scroll view after all).

Good things about the second solution: a) I like it; b) I use it a lot; and c) when you tell the grid view to scroll to CGPointZero, it scrolls to the correct position, and inertial scrolling will bounce the entire view back to the correct position too.

**Comment by evadne** [comment]
Closing as Workaround Provided.  Feel free to re-open this issue :)
