### ISSUE TITLE
Cell changes on click

### ISSUE THREAD

**Issue by pailoro** [AlanQuatermain/AQGridView#83]
Hi, I'm getting this problem:

When I click in a cell, appears one color on top of elements.

Just like that http://cl.ly/07442C0c0w1t3H2B1B1W

Wich value I have to change to fix this?

Thanks!

**Comment by evadne** [comment]
Are you putting stuff in the contentView, not the cell itself?

-ev

**Comment by pailoro** [comment]
Nops. Just in the cell nib item. I think it could be some function. Because it just happen on click, and when I click again, it disappears.

**Comment by pailoro** [comment]
I just solved it. I commented the lines:

//   UIView *addedView = [[UIView alloc] initWithFrame: self.bounds];
//   addedView.backgroundColor = [UIColor whiteColor]; 

//   [self setContentView:addedView];

in
- (UIView *) contentView
