### ISSUE TITLE
Potential Leak

### ISSUE THREAD

**Issue by funkyboy** [AlanQuatermain/AQGridView#9]
The static analyzer detects a potential leak on the last line of this method: 
- (NSSet *) animateCellUpdatesUsingVisibleContentRect: (CGRect) contentRect

**Comment by AlanQuatermain** [comment]
I've fixed that one locally I think; I'm due to push the Kobo version sometime soon— probably tomorrow, since it's iPhone 4 day and we've got the company BBQ in the afternoon so no-one will be committing anything of great importance ;)

**Comment by AlanQuatermain** [comment]
No more analyzer errors showing up since last week's code dump, so I'm closing this here.
