### ISSUE TITLE
How to add header in gridview

### ISSUE THREAD

**Issue by 007lock** [AlanQuatermain/AQGridView#97]
Hi, 
Please help me add header view on top of the gridview like a search view into AQGridView?

Thanks,
Simon

**Comment by evadne** [comment]
Does `gridHeaderView` work?

**Comment by sikosis** [comment]
I was wondering if this was working too ?

**Comment by 007lock** [comment]
Thanks for your support, it's working property. I've just confuse how to remove scroll vertical bounce of gridview.

**Comment by evadne** [comment]
Closing as resolved.
